### ISSUE TITLE
Add vehicle name, colour and plate to the notification

### ISSUE THREAD

**Issue by DokaDoka** [Sov-Nation/dd_outlawalerts#2]
Random chance will determine if any additional details are included

Will need a lot of text wrangling

**Comment by DokaDoka** [comment]
Use
GetVehicleColours
GetVehicleNumberPlateText

**Comment by DokaDoka** [comment]
I have all the information grabbed successfully but I'm not sure how to implement it when it comes to the actual notification, I don't want to include all of the info all of the time

**Comment by DokaDoka** [comment]
So now that I have changed the way the notification text is squished together I think it should be easier to accomplish this. I have a bit of an idea of how I'll get it to work, some loops and some nil values in the middle of the string tables. I'd like to get your thoughts on a few things @Soverign92 

Currently we have the standard notification
- shots fired by a <sex> at <street>

that's the same whether or not the perp is on foot and that's a bit boring.

So the plan is to insert this additional information of model, plate and colour in the middle of the notification sometimes to spice things up. But the question is how often should this happen and should there be a hierarchy of information or should it just be random?

**Comment by Soverign92** [comment]
I kind of like random because people don't always call in the same information. If there is a hierarchy of information I think the vehicle type is most important followed by everything else. Example. 

"We have reports of a drive by shooting in chamberlain hills. The vehicle is described as a blue Vapid Dominator 752 CUX driven by a white male."

**Comment by DokaDoka** [comment]
Alright, I'll hopefully get it bashed out soon
Also that's a good point I should add make
