### ISSUE TITLE
Implement department choice

### ISSUE THREAD

**Issue by DokaDoka** [Sov-Nation/dd_outlawalerts#3]
need to decide if it's everything, blips, notifications and sound or if it's something else and what to do about the scanner

**Comment by DokaDoka** [comment]
ok, after some thinking, 

- scanner shows all text alerts
- possibly add a radio item for audio alerts but that's a while away
- will need to go through the zones table and divide it up into jurisdictions, could also come with a revision of the popzones table
- blips will be shown regardless of jurisdiction 
- so this will only affect text and audio alerts

**Comment by Soverign92** [comment]
I already have a base for jurisdictions. I will send it to you when I find it. Need to look at the clutter folders of mine.

**Comment by DokaDoka** [comment]
@Soverign92 any luck on here, I'd like to move forward with this

**Comment by Soverign92** [comment]
@DokaDoka I have looked for the chart I made and all I was able to find was one of patrol zones for Los Santos. I need to remake it. I can do that either tonight or somtime tomorrow and post the image here.

**Comment by DokaDoka** [comment]
alright cool I can work with that

**Comment by Soverign92** [comment]
Green = Polito Bay
Pink = Grapeseed
Purple = Sandy Shores
Blue = LSPD
Black = Zancudo
Sheriff and SASP = Whole Map. 

![Jurisdictions](https://user-images.githubusercontent.com/72425930/95802702-d1073a80-0cc3-11eb-980e-5bf707abea38.png)

**Comment by DokaDoka** [comment]
So I've done it by zone, by default the agency for that zone will get the alert, LSPD takes the city and everything else is BCSO for now. Changing the agency for the zone in the config is trivial, we can even assign a group to a zone.
